### ISSUE TITLE
how to compile the code on mac os x

### ISSUE THREAD

**Issue by thegodone** [tvercaut/LSQR-cpp#4]
On the terminal a make do nothing. Any idea how I can compile the code ?

**Comment by tvercaut** [comment]
The project uses `cmake` as a build process manager. Please have a look at the [corresponding documentation](https://cmake.org/runningcmake/). You basically need to run:
```
mkdir <build-directory>
cd <build-directory>
ccmake <source-directory>
make
```
This is after having installed cmake.
